### ISSUE TITLE
(StreamPipeSink) Pipe is broken

### ISSUE THREAD

**Issue by JensPLarsen** [rosenbjerg/FFMpegCore#130]
Hello, 

I am experiencing an issue where I cannot get the StreamPipeSink to work. 

```CSharp
Stream input = File.OpenRead("video.ts");  // Will get it from an online source
StreamPipeSource pipeSource = new StreamPipeSource(input);

var output = new MemoryStream();
StreamPipeSink pipeSink = new StreamPipeSink(output);

//Exctract audio to a MemoryStream --> byte[ ]
FFMpegArguments
    .FromPipeInput(pipeSource)
    .OutputToPipe(pipeSink, options => options.WithCustomArgument("-acodec pcm_s16le -osr 16000 -ocl mono"))
    .ProcessSynchronously();
```

This results in an error: 
```
 Pipe is broken.
   at FFMpegCore.Arguments.InputPipeArgument.ProcessDataAsync(CancellationToken token) in C:\dev\FFMpegCore\FFMpegCore\FFMpeg\Arguments\InputPipeArgument.cs:line 27
   at FFMpegCore.Arguments.PipeArgument.During(CancellationToken cancellationToken) in C:\dev\FFMpegCore\FFMpegCore\FFMpeg\Arguments\PipeArgument.cs:line 41
   at FFMpegCore.FFMpegArguments.During(CancellationToken cancellationToken) in C:\dev\FFMpegCore\FFMpegCore\FFMpeg\FFMpegArguments.cs:line 73
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at FFMpegCore.FFMpegArgumentProcessor.ProcessSynchronously(Boolean throwOnError) in C:\dev\FFMpegCore\FFMpegCore\FFMpeg\FFMpegArgumentProcessor.cs:line 64
   --- End of inner exception stack trace ---
   at FFMpegCore.FFMpegArgumentProcessor.HandleException(Boolean throwOnError, Exception e, IReadOnlyList`1 errorData) in C:\dev\FFMpegCore\FFMpegCore\FFMpeg\FFMpegArgumentProcessor.cs:line 150
   at FFMpegCore.FFMpegArgumentProcessor.ProcessSynchronously(Boolean throwOnError) in C:\dev\FFMpegCore\FFMpegCore\FFMpeg\FFMpegArgumentProcessor.cs:line 73
```

My own throughts:
I have been digging around a bit.
The `FFMpegArgumentProcessor.ProcessSynchronously(...)` calls the ` cancellationTokenSource.Cancel()` before the `OutputPipeArgument.ProcessDataAsync(...)` is finished, means no data have been read.

```csharp 
 try
            {
                _ffMpegArguments.Pre();
                await Task.WhenAll(instance.FinishedRunning().ContinueWith(t =>
                {
                    errorCode = t.Result;
                    cancellationTokenSource.Cancel();
                    _ffMpegArguments.Post();
                }), _ffMpegArguments.During(cancellationTokenSource.Token)).ConfigureAwait(false);
            }
```
And it the `PipeArgument.Post()` is called before the `OutputPipeArgument.ProcessDataAsync(...)` is finished too (due to the async nature of async). Even through `cancellationTokenSource.Cancel();` have been called

Due to `PipeArgument.Post()` does:
```csharp
   public void Post()
        {
            Pipe?.Dispose();
            Pipe = null!;
        }
```
Means the pipe is null.

The last thing `PipeArgument.During(...)` does is calling:
```csharp
 Pipe.Disconnect();
```` 
But at this point the pipe is already null, hence the error.

**Comment by JensPLarsen** [comment]
I have tested using `OutputToFile(...)` which does works.

```csharp
Stream input = File.OpenRead("video.ts");  // Will get it from an online source
StreamPipeSource pipeSource = new StreamPipeSource(input);

// var output = new MemoryStream();
// StreamPipeSink pipeSink = new StreamPipeSink(output);

FFMpegArguments
    .FromPipeInput(pipeSource)
    //.OutputToPipe(pipeSink, options => options.WithCustomArgument("-acodec pcm_s16le -osr 16000 -ocl mono"))
    .OutputToFile("output.wav", true, options => options.WithCustomArgument("-acodec pcm_s16le -osr 16000 -ocl mono"));
    .ProcessSynchronously();
```
But I would prefer using `OutputToPipe` so there are no actual files

**Comment by renanrcp** [comment]
Same problem with output args: `-ac 2 -acodec libopus` and works fine with `OutputToFile(...)`

**Comment by rosenbjerg** [comment]
Could one of you provide an minimal example that reproduces this behaviour? That would make it much easier to debug
Fx. a github repro containing the code and some (small) sample files that yields this behavior.
Or even better; a PR with a unit test that fails due to this error

**Comment by renanrcp** [comment]
I do this [repo](https://github.com/renanrcp/FFMpegCoreBugRepo) with 3 broken pipes example and one working (just decoding, if you try encoding will broke)

**Comment by renanrcp** [comment]
I get this on FFMpegException#FFMpegErrorOutput

ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[mp3 @ 0x556b07c20740] invalid concatenated file detected - using bitrate for duration
Input #0, mp3, from 'unix:/tmp/CoreFxPipe_FFMpegCore_89ee8bae-82dc-43ab-b6d0-0dac7aed5827':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf55.15.100
  Duration: N/A, start: 0.023021, bitrate: 128 kb/s
    Stream #0:0: Audio: mp3, 48000 Hz, stereo, fltp, 128 kb/s
[NULL @ 0x556b07c25b40] Unable to find a suitable output format for 'unix:/tmp/CoreFxPipe_FFMpegCore_60e48937-baa1-4b7f-9424-96c2a6f5e00a'
unix:/tmp/CoreFxPipe_FFMpegCore_60e48937-baa1-4b7f-9424-96c2a6f5e00a: Invalid argument

**Comment by renanrcp** [comment]
A temporary solution is use -f instead -acoded

Example: 


                var processor = FFMpegArguments
                .FromPipeInput(new StreamPipeSource(file))
                .OutputToPipe(new StreamPipeSink(outputStream), options =>
                {
                    options.WithAudioCodec("libopus");
                });

to

                var processor = FFMpegArguments
                .FromPipeInput(new StreamPipeSource(file))
                .OutputToPipe(new StreamPipeSink(outputStream), options =>
                {
                    options.WithCustomArgument("-f opus");
                });

**Comment by renanrcp** [comment]
The same problem appears debugging `FFProbe.Analyse(...)`

[mp3 @ 0x55a094083f00] invalid concatenated file detected - using bitrate for duration

The audio duration will be 0, FFmpeg doesn't respond with the correct duration in JSON response.

**Comment by renanrcp** [comment]
I tried with raw ffmpeg process with this code:


            using var sourceStream = File.Open(AudioFilePath, FileMode.Open);

            using var process = Process.Start(new ProcessStartInfo
            {
                FileName = "ffprobe",
                Arguments = $"-i -",
                UseShellExecute = false,
                RedirectStandardInput = true,
            });

            await sourceStream.CopyToAsync(process.StandardInput.BaseStream);

            await process.StandardInput.BaseStream.FlushAsync();

            await process.WaitForExitAsync();

received the same error, sorry don't know what the problem here, seems a ffmpeg/pipe problem

**Comment by rosenbjerg** [comment]
> I get this on FFMpegException#FFMpegErrorOutput
> 
> ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
> built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
> configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
> libavutil 56. 31.100 / 56. 31.100
> libavcodec 58. 54.100 / 58. 54.100
> libavformat 58. 29.100 / 58. 29.100
> libavdevice 58. 8.100 / 58. 8.100
> libavfilter 7. 57.100 / 7. 57.100
> libavresample 4. 0. 0 / 4. 0. 0
> libswscale 5. 5.100 / 5. 5.100
> libswresample 3. 5.100 / 3. 5.100
> libpostproc 55. 5.100 / 55. 5.100
> [mp3 @ 0x556b07c20740] invalid concatenated file detected - using bitrate for duration
> Input #0, mp3, from 'unix:/tmp/CoreFxPipe_FFMpegCore_89ee8bae-82dc-43ab-b6d0-0dac7aed5827':
> Metadata:
> major_brand : isom
> minor_version : 512
> compatible_brands: isomiso2avc1mp41
> encoder : Lavf55.15.100
> Duration: N/A, start: 0.023021, bitrate: 128 kb/s
> Stream #0:0: Audio: mp3, 48000 Hz, stereo, fltp, 128 kb/s
> [NULL @ 0x556b07c25b40] Unable to find a suitable output format for 'unix:/tmp/CoreFxPipe_FFMpegCore_60e48937-baa1-4b7f-9424-96c2a6f5e00a'
> unix:/tmp/CoreFxPipe_FFMpegCore_60e48937-baa1-4b7f-9424-96c2a6f5e00a: Invalid argument

To fix this error, you need to add .ForceFormat("wav"), which gives ffmpeg `-f wav`. ffmpeg normally uses the extension of the output file path to determine the format. When outputting to a stream, that is not possible and that will almost always require it to be specified.

FFMpegCore does not use StandardInput.BaseStream to "pass along" the input stream. Instead it uses NamedPipeServerStream, which btw uses unix sockets on non-Windows machines

**Comment by rosenbjerg** [comment]
@renanrcp I was able to fix PipeBroken1Async and PipeBroken2Async just by adding .ForceFormat("opus") and .ForceForce("mp3").
I'm looking into PipeBroken3Async since that one gives a null ref exception after adding ForceFormat("raw") to input and ForceFormat("opus") to output

**Comment by renanrcp** [comment]
yeah, that fixed here, about `FFProbe.Analyse(...)` you know any fix?

**Comment by rosenbjerg** [comment]
I am unable to replicate. Both of these work, using the mp3 file included in your sample repo
```csharp
FFProbe.Analyse(MP3_PATH);
await FFProbe.AnalyseAsync(MP3_PATH);
```
Using your sample repo

**Comment by renanrcp** [comment]
Can you test using a stream?

**Comment by dormalexis** [comment]
Hello ! I am experiencing the same issue with the Analyse methods. I tried using a file path and a stream but it didn't work in both  cases. It seems the file isn't found but the url I provide is working.. And the stream exists too

**Comment by rosenbjerg** [comment]
@dormalexis Could  you give an example of what you are trying?

**Comment by rosenbjerg** [comment]
@renanrcp I get a NullRefException using:
```csharp
await using (var stream = File.OpenRead(MP3_PATH))
{
    var result = FFProbe.Analyse(stream);
    Console.WriteLine(result.Duration);
}
```
Is that the problem you experienced?

**Comment by renanrcp** [comment]
@rosenbjerg I made one commit to the https://github.com/renanrcp/FFMpegCoreBugRepo
In your code I think it's a bug with threads completion (one pipe finish before another and causes a null reference)
My code using AnalyseAsync the problem is the duration, when I use file paths the duration should return correctly, but with streams it always return an empty timespan like 00:00:00

**Comment by rosenbjerg** [comment]
@renanrcp could you try using version 3.2.2 or newer?

**Comment by renanrcp** [comment]
I'm tried in the same [repo](https://github.com/renanrcp/FFMpegCoreBugRepo) with the newer version (3.2.4), and the error keeps happening

**Comment by gabilan** [comment]
@rosenbjerg Trying to give some support and context here. I think the pipe support may need to be re-worked. NamedPipeServerStream isn't really as cross-platform compatible as one would expect. I'm on MacOS Big Sur and the input pipes, etc don't work at all -- for any use case.

1. I first ran into a .NET Core issue you tried to fix for MacOS saying the name was too long for the platform.
2. After patching that, I started getting errors from FFmpeg saying the file (pipe) didn't exist.

I dug into "why" the second issue by looking at tickets filed against the .NET Core team. They have similar tickets to this one for FFmpeg and named pipes (I've linked to it below). On Unix platforms named pipes aren't pipes at all but are instead domain sockets -- and the filename was/is just a convenience that is apparently broken on MacOS (for me anyways). Because of all that, I rolled a replacement for the PipeArgument implementations that uses a TcpListener/TcpClient instead of a NamedPipeServerStream. FFMpeg supports TCP inputs and outputs natively, so no trickery was necessary. I can send a PR for your review or inspiration if you'd like.

I'm posting here because I think my PR addresses this issue and the MacOS issues you've been trying to chase down. One change I made was to initialize the TCP listener in the Pre() method. I also added CancellationToken on this method/interface so that it could be cancelled (if necessary). I moved Pre() before the FFMpeg instance was started. I needed to make this change because it was causing issues on my system; FFMpeg consistently started execution before the FFmpegCore pipeline got to the During() phase.

Reference: https://github.com/dotnet/runtime/issues/28979

**Comment by vicente-da-silva** [comment]
I'm struggling to get the following working on .net5, running on raspbian, it seems related to Streams as well.

The following works
await FFMpegArguments
                     .FromFileInput("output.h264")
                     .OutputToFile("output.mp4", true, options => options
                        .WithCustomArgument("-c:v copy -f mp4"))
                    .ProcessAsynchronously();

The following doesn't
await FFMpegArguments
                     .FromPipeInput(new StreamPipeSource(inputStream))
                     .OutputToPipe(new StreamPipeSink(outputStream), options => options
                        .WithCustomArgument("-c:v copy -f mp4"))
                     .ProcessAsynchronously();

Both streams are Memory streams, I have checked the input stream by writing it to a file and converting it in a terminal session to mp4, which works fine.

Here is the error output
ffmpeg version 4.1.6-1~deb10u1+rpt1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8 (Raspbian 8.3.0-6+rpi1)
...
unix:/tmp/CoreFxPipe_FFMpegCore_4ece6280-4850-43df-9d45-72e128a0cddf: Invalid data found when processing input
[2020/12/17 16:26:40.400] [Program]

**Comment by gabilan** [comment]
@vicente-da-silva You can try applying my patch and see if it works for you on Linux. Unzip and then run `git apply streams.patch`.
[streams.patch.zip](https://github.com/rosenbjerg/FFMpegCore/files/5711162/streams.patch.zip)

**Comment by rosenbjerg** [comment]
@vicente-da-silva One problem that I am seeing is that you are trying to a stream, which the mp4 muxer in ffmpeg does not support. It requires the output to be seekable, and even though MemoryStream are seekable using C# methods, I do not think that will be the case for the exposed NamedPipeServerStream, since they are unidirectional.
If you need to been able to output to a stream, you need to use a format that ffmpeg supports streaming output for. You can use webm for this.

**Comment by rosenbjerg** [comment]
@gabilan I am aware that NamedPipeServerStream uses unix sockets on unix, but the unit tests are running, and passing, on both windows and linux. But I was not aware that support is broken on macos.
I am however quite interested in your suggestion to use tcp sockets. I would assume that there is more overhead in using a tcp socket vs a unix socket, but that might not be the case?
Your problems with unix sockets seems to be more related to path being incorrect on macos, than with the cross-compatibility with unix sockets. It may even be related to underlying changes in the big sur upgrade which the dotnet runtime team hasn't gotten around to fix yet. 
I am surprised to hear you got the path length exception; that should be fixed now that we don't use Path.GetTempPath anymore because it resulted in the current user's tmp folder, instead of the "real" /tmp dir. So the problem might be that the dotnet runtime now places the "convenience file" in the current user's tmp folder instead of the expected /tmp

**Comment by gabilan** [comment]
@rosenbjerg Yeah, they aren't placing it in /tmp as you'd expect -- but some other user-specific path. And yes, I also believe that totally not working anymore is due to the BigSur upgrade. The "file" exists, but FFMpeg can't read/find it at all.

TCP performance is worse than unix domain sockets. I've seen reports/estimates that unix domain sockets offer between 2x-7x more throughput than a TCP loopback connection. For me, this is not an issue. For my use case, a loopback connection sending 30 FPS isn't taxing enough to warrant concern; it takes more time to encode the frame than it does to send the raw bytes for it. For high-throughput IPC I wouldn't recommend it over unix domain sockets. TCP is slightly less brittle than the named pipes though, only because of the naming conventions that are out of our control. 

I only offer my patch as inspiration; I quickly threw something together for my own issues and it's working for me now.

**Comment by vicente-da-silva** [comment]
@rosenbjerg , you are correct, I tried a test today from a file input to a output memory stream and got the following
[mp4 @ 0xd1b9d0] muxer does not support non seekable output. 
However, I still have the input stream problem as mentioned previously.
@rosenbjerg @gabilan Is there any other way for me to get H264 encoded video (fetched in real time from the raspberry pi camera) to real time MP4 format? I want to be able to view a live stream of the video coming from the pi. I have the web server and camera portion working, the conversion is the last piece of the puzzle.

**Comment by rosenbjerg** [comment]
@vicente-da-silva Why does it need to be mp4? And is the input really mp4? If it is coming straight from a camera input I would expect it to be raw

**Comment by rosenbjerg** [comment]
Closing this one

@vicente-da-silva you could look into gstreamer? That might support your use-case
